/**
 * KIR → C code emitter.
 *
 * Takes a de-SSA'd KirModule and produces a string of valid C code.
 * Expects phi nodes to have already been eliminated by the de-SSA pass.
 */

import type { KirModule } from "../kir/kir-types.ts";
import runtimeHeaderSource from "../runtime/runtime.h" with { type: "text" };
import { emitExtern, emitFunctionPrototype, emitGlobal, emitTypeDecl } from "./c-emitter-decls.ts";
import { emitFunction } from "./c-emitter-fn.ts";
import { sanitizeName } from "./c-emitter-types.ts";

// ─── Runtime header (embedded at build time via Bun text import) ────────────
// Embedding avoids the runtime fs read that broke when the compiler was
// shipped without its source tree alongside the binary.

const RUNTIME_HEADER = `/* Generated by the Kei compiler */\n${runtimeHeaderSource}`;

// ─── Main emitter ───────────────────────────────────────────────────────────

export function emitC(module: KirModule): string {
  const out: string[] = [];

  out.push(RUNTIME_HEADER);

  // Forward-declare structs
  for (const td of module.types) {
    if (td.type.kind === "struct") {
      out.push(`struct ${sanitizeName(td.name)};`);
    }
  }
  if (module.types.length > 0) out.push("");

  // Type definitions
  for (const td of module.types) {
    out.push(emitTypeDecl(td));
    out.push("");
  }

  // Extern declarations
  for (const ext of module.externs) {
    out.push(emitExtern(ext));
  }
  if (module.externs.length > 0) out.push("");

  // Forward-declare all functions
  for (const fn of module.functions) {
    out.push(`${emitFunctionPrototype(fn)};`);
  }
  if (module.functions.length > 0) out.push("");

  // Global variables
  for (const g of module.globals) {
    out.push(emitGlobal(g));
  }
  if (module.globals.length > 0) out.push("");

  // Function definitions
  for (const fn of module.functions) {
    out.push(emitFunction(fn));
    out.push("");
  }

  return out.join("\n");
}
