export type {
  BinOp,
  BlockId,
  KirArrayType,
  KirAssertCheck,
  KirBinOp,
  KirBitNot,
  KirBlock,
  KirBoolType,
  KirBoundsCheck,
  KirBranch,
  KirCall,
  KirCallExtern,
  KirCallExternVoid,
  KirCallVoid,
  KirCast,
  KirConstBool,
  KirConstFloat,
  KirConstInt,
  KirConstNull,
  KirConstString,
  KirEnumType,
  KirExtern,
  KirField,
  KirFieldPtr,
  KirFloatType,
  KirFunction,
  KirFunctionType,
  KirGlobal,
  KirIndexPtr,
  KirInst,
  KirIntType,
  KirJump,
  KirLoad,
  KirModule,
  KirNeg,
  KirNot,
  KirNullCheck,
  KirOverflowCheck,
  KirParam,
  KirPhi,
  KirPtrType,
  KirRequireCheck,
  // Terminators
  KirRet,
  KirRetVoid,
  KirSizeof,
  // Instructions
  KirStackAlloc,
  KirStore,
  KirStringType,
  KirStructType,
  KirSwitch,
  KirTerminator,
  KirType,
  KirTypeDecl,
  KirUnreachable,
  KirVariant,
  KirVoidType,
  VarId,
} from "./kir-types.ts";

export { KirLowerer, lowerModulesToKir, lowerToKir } from "./lowering.ts";
export { runMem2Reg } from "./mem2reg.ts";
export { printKir, printType } from "./printer.ts";
