/* Generated by the Kei compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

typedef const char* kei_string;

static void kei_panic(const char* msg) {
    fprintf(stderr, "panic: %s\n", msg);
    exit(1);
}

static void kei_print_string(kei_string s) {
    printf("%s\n", s);
}

static void kei_print_int(int64_t v) {
    printf("%lld\n", (long long)v);
}

static void kei_print_float(double v) {
    printf("%g\n", v);
}

static void kei_print_bool(bool v) {
    printf("%s\n", v ? "true" : "false");
}

static void kei_bounds_check(int64_t index, int64_t length) {
    if (index < 0 || index >= length) {
        fprintf(stderr, "panic: index out of bounds: index %lld, length %lld\n",
                (long long)index, (long long)length);
        exit(1);
    }
}

static void kei_null_check(const void* ptr) {
    if (ptr == NULL) {
        kei_panic("null pointer dereference");
    }
}

static void kei_assert(bool cond, const char* msg) {
    if (!cond) {
        fprintf(stderr, "assertion failed: %s\n", msg);
        exit(1);
    }
}

static void kei_require(bool cond, const char* msg) {
    if (!cond) {
        fprintf(stderr, "requirement failed: %s\n", msg);
        exit(1);
    }
}

int main(void);
void number_tests(void);
void string_tests(void);

int main(void) {
    kei_string _v1;
    int32_t _v3;
    double _v5;
    bool _v7;
    int32_t _v10;
    int32_t _v11;
    int32_t _v13;
    int32_t _v14;
    int32_t _v15;

entry: ;
    _v1 = "Hello, World!";
    _v3 = 42;
    _v5 = 3.14159;
    _v7 = true;
    if (_v7) goto if_then_0; else goto if_else_1;
if_then_0:
    kei_print_string(_v1);
    _v10 = 0;
    _v11 = 1;
    _v13 = _v3 + _v11;
    _v14 = 0;
    return _v14;
if_else_1:
    _v15 = 1;
    return _v15;
if_end_2:
    __builtin_unreachable();
}

void number_tests(void) {
    int32_t _v1;
    int32_t _v3;
    int32_t _v5;
    int32_t _v7;
    double _v9;

entry: ;
    _v1 = 1000000;
    _v3 = (int32_t)4293844428ULL;
    _v5 = 161;
    _v7 = 493;
    _v9 = 1.5e-10;
    return;
}

void string_tests(void) {
    kei_string _v1;
    kei_string _v3;
    kei_string _v5;
    kei_string _v7;

entry: ;
    _v1 = "line1\nline2\r\nline3";
    _v3 = "He said \"Hello world\"";
    _v5 = "Hello";
    _v7 = "Path: C:\\Users\\file.txt\t(tab)\0";
    return;
}
